id: create-environment
name: Create new environment
description: Create an environment in an application.
on:
  path_call:
    inputs:
      app:
        type: string
        required: true
        description: Name of the application to add an environment to
      env_name:
        type: string
        required: true
        description: Name of the environment to create
      env_type:
        type: string
        required: true
        description: Type of environment (e.g. development, staging, production)
      from_env:
        type: string
        required: false
        description: Optional existing environment to copy from

timeout-minutes: 30

jobs:
  create-environment:
    name: Create environment
    needs: validate-inputs
    steps:
      - id: create-env
        name: Create environment
        uses: humanitec/create-environment
        with:
          app: ${{ inputs.app }}
          env_name: ${{ inputs.env_name }}
          env_type: ${{ inputs.env_type }}
    outputs:
      env_id: ${{ steps.create-env.outputs.env_id }}
