id: create-application
name: Create Application
description: Create a new application.
on:
  path_call:
    inputs:
      app_id:
        type: string
        description: "Application ID to create"
        required: true
      app_name:
        type: string
        description: "Friendly name for the application"
        required: true
      env_type:
        type: string
        description: "Environment type for the initial environment"
        required: true
      create_initial_env:
        type: boolean
        description: "Whether to create an initial environment"
        required: false

jobs:
  create-app:
    name: Create Humanitec Application
    steps:
      - id: create-app
        name: Create the application
        uses: humanitec/cli-action
        with:
          command: create app ${inputs.app_id} --name "${inputs.app_name}"
